//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

pub use super::album::Entity as Album;
pub use super::album_tag_relation::Entity as AlbumTagRelation;
pub use super::disc::Entity as Disc;
pub use super::tag_info::Entity as TagInfo;
pub use super::tag_relation::Entity as TagRelation;
pub use super::track::Entity as Track;
