//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tag_info")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    #[sea_orm(column_type = "custom(\"enum_text\")")]
    pub r#type: String,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::album_tag_relation::Entity")]
    AlbumTagRelation,
}

impl Related<super::album_tag_relation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlbumTagRelation.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
