//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, async_graphql :: SimpleObject)]
#[sea_orm(table_name = "track")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub album_db_id: i64,
    pub disc_db_id: i64,
    pub title: String,
    pub artist: String,
    #[sea_orm(column_type = "custom(\"enum_text\")")]
    pub r#type: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::album::Entity",
        from = "Column::AlbumDbId",
        to = "super::album::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Album,
    #[sea_orm(
        belongs_to = "super::disc::Entity",
        from = "Column::DiscDbId",
        to = "super::disc::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Disc,
}

impl Related<super::album::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Album.def()
    }
}

impl Related<super::disc::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Disc.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::album::Entity")]
    Album,
    #[sea_orm(entity = "super::disc::Entity")]
    Disc,
}
