//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "track")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub album_db_id: i32,
    pub disc_db_id: i32,
    pub index: i32,
    pub title: String,
    pub artist: String,
    pub artists: Option<Json>,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    #[sea_orm(column_type = "custom(\"enum_text\")")]
    pub r#type: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::album::Entity",
        from = "Column::AlbumDbId",
        to = "super::album::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Album,
    #[sea_orm(has_many = "super::album_tag_relation::Entity")]
    AlbumTagRelation,
    #[sea_orm(
        belongs_to = "super::disc::Entity",
        from = "Column::DiscDbId",
        to = "super::disc::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Disc,
}

impl Related<super::album::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Album.def()
    }
}

impl Related<super::album_tag_relation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlbumTagRelation.def()
    }
}

impl Related<super::disc::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Disc.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
