[package]
name = "annil"
version = "0.1.0"
authors = ["Yesterday17 <t@yesterday17.cn>"]
edition = "2018"

[dependencies]
actix-web = { version = "4.0.0-beta.4", features = ["tls-rustls"] }
anni-backend = { path = "../anni-backend" }
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.6.3", features = ["io"] }
anyhow = "1.0"
async-trait = "0.1.45"

serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
sqlx = { version = "0.5", features = ["postgres", "runtime-actix-rustls", "ipnetwork", "uuid", "chrono"] }
uuid = { version = "0.8", features = ["serde", "v4"] }
env_logger = "0.8.3"
jwt-simple = "0.9"
