[package]
name = "annil"
version = "0.1.0"
authors = ["Yesterday17 <mmf@mmf.moe>"]
edition = "2018"

[dependencies]
actix-web = { version = "4.0.0-beta.8", features = ["rustls"] }
actix-cors = "0.6.0-beta.2"
anni-backend = { path = "../anni-backend" }
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.6.3", features = ["io"] }
anyhow = "1.0"
async-trait = "0.1.45"

serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
log = "0.4.0"
env_logger = "0.8.3"
jwt-simple = "0.9"
