[package]
name = "annil"
version = "0.1.0"
authors = ["Yesterday17 <mmf@mmf.moe>"]
edition = "2018"

[dependencies]
actix-web = { version = "4.0.1", features = ["rustls"] }
actix-cors = "0.6.1"

anni-provider = { path = "../anni-provider" }
actix-utils = "3.0.0"
parking_lot = "0.12.0"

tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7.2", features = ["io"] }
futures = "0.3"
anyhow = "1.0"
thiserror = "1.0"
async-trait = "0.1"
anni-flac = { path = "../anni-flac", features = ["async"] }
anni-repo = { path = "../anni-repo", features = ["git", "db-write"] }

serde = { version = "1.0", features = ["derive"] }
toml_edit = "0.14.4"
log = "0.4.0"
env_logger = "0.9.0"
jwt-simple = "0.11.0"
uuid = "1"
base64 = "0.13.0"
