[package]
name = "annil"
version = "0.1.0"
authors = ["Yesterday17 <mmf@mmf.moe>"]
edition = "2021"

[dependencies]
actix-web = { version = "4.2.1", features = ["rustls"] }
actix-cors = "0.6.4"
actix-utils = "3.0.1"

parking_lot = "0.12.0"

tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7.4", features = ["io"] }
futures = "0.3"
anyhow = { version = "1.0", features = ["backtrace"] }
thiserror = "1.0"
async-trait = "0.1"

anni-flac = { path = "../anni-flac", version = "0.2.2", features = ["async"] }
anni-repo = { path = "../anni-repo", version = "0.1.1", features = ["git", "db-write"] }
anni-provider = { path = "../anni-provider", version = "0.1.1" }

serde = { version = "1.0", features = ["derive"] }
toml_edit = { version = "0.14.4", features = ["easy"] }
log = "0.4"
env_logger = "0.9.0"
jwt-simple = "0.11.0"
uuid = "1"
base64 = "0.13.0"
