[package]
name = "annil"
version = "0.1.0"
authors = ["Yesterday17 <mmf@mmf.moe>"]
edition = "2018"

[dependencies]
actix-web = { version = "4.0.0-beta.14", features = ["rustls"] }
actix-cors = "0.6.0-beta.6"
anni-provider = { path = "../anni-provider" }
actix-utils = "3.0.0"

tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.6.3", features = ["io"] }
futures = "0.3"
anyhow = "1.0"
thiserror = "1.0"
async-trait = "0.1.45"
anni-flac = { path = "../anni-flac", features = ["async"] }
anni-repo = { path = "../anni-repo", features = ["git", "db"] }

serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
log = "0.4.0"
env_logger = "0.8.3"
jwt-simple = "0.9"
