[package]
name = "anni-backend"
version = "0.1.0"
authors = ["Yesterday17 <t@yesterday17.cn>"]
edition = "2018"

[dependencies]
tokio = { version = "1", features = ["full"] }
async-trait = "0.1.45"
thiserror = "1.0"
anni-repo = { path = "../anni-repo" }
