[package]
name = "anni-clap-handler-derive"
version = "0.1.0"
edition = "2018"

[dependencies]
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
proc-macro-error = "1.0"

[lib]
proc-macro = true
