[package]
name = "anni-clap-handler"
version = "0.1.0"
edition = "2018"

[dependencies]
anni-clap-handler-derive = { path = "../anni-clap-handler-derive" }
async-trait = { version = "0.1.52", optional = true }
anyhow = "1.0"

[features]
default = []
async = ["async-trait"]

