[package]
name = "anni-common"
version = "0.1.1"
authors = ["Yesterday17 <mmf@mmf.moe>"]
edition = "2018"

[features]
default = ["trash"]
arc = []

[dependencies]
byteorder = "1"
thiserror = "1.0"
chardetng = "0.1.17"
path-absolutize = "3.0.13"
pathdiff = "0.2.1"
log = "0.4.0"
anni-artist = { git = "https://github.com/ProjectAnni/anni-artist" }

regex = "1"
lazy_static = "1.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

trash = { version = "2.0", optional = true }