[package]
name = "anni-common"
version = "0.1.1"
authors = ["Yesterday17 <mmf@mmf.moe>"]
edition = "2018"

[features]
default = []
arc = []

[dependencies]
anyhow = "1.0"
byteorder = "1"
thiserror = "1.0"
chardetng = "0.1.12"
log = "0.4.0"
encoding_rs = "=0.8.28"

regex = "1"
lazy_static = "1.4.0"
serde = { version = "1.0", features = ["derive"] }

trash = "2.0"