[package]
name = "anni-repo"
version = "0.1.0"
authors = ["Yesterday17 <t@yesterday17.cn>"]
edition = "2018"

[dependencies]
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
regex = "1"
anyhow = "1.0"
thiserror = "1.0"
anni-common = { path = "../anni-common" }
anni-derive = { path = "../anni-derive" }