[package]
name = "anni-repo"
version = "0.1.1"
authors = ["Yesterday17 <mmf@mmf.moe>"]
edition = "2021"

description = "Operate on anni metadata repository."
repository = "https://github.com/ProjectAnni/anni"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
toml_edit = "0.19.0"
# TODO: remove usage of toml, use toml_edit directly
toml = "0.7.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", optional = true }
regex = "1"
thiserror = "1.0"
anni-common = { version = "0.1.1", path = "../anni-common", default-features = false }
uuid = { version = "1", features = ["v4", "serde"] }
log = "0.4"
once_cell = "1"
pathdiff = "0.2.1"
indexmap = "1.9.1"
anni-artist = "0.1.1"

# flac
anni-flac = { version = "0.2.2", path = "../anni-flac", optional = true }

# Git related
git2 = { version = "0.15", optional = true, default-features = false, features = [
    "vendored-libgit2",
] }
git2-ureq = { version = "0.2.0", optional = true, features = ["socks-proxy"] }

# SQLite related
rusqlite = { version = "0.28.0", optional = true, features = [
    "uuid",
    "bundled",
    "serde_json",
] }
serde_rusqlite = { version = "0.31.0", optional = true }

# Search
tantivy = { version = "0.19.0", optional = true }
lindera-tantivy = { version = "0.19.0", optional = true, features = ["ipadic"] }


# WASM dependencies
# comment those dependencies when publishing to crates.io
[target.wasm32-unknown-unknown.dependencies]
getrandom = { version = "0.2", features = ["js"] }
js-sys = "0.3.56"
wasm-bindgen = { version = "0.2.79", features = ["serde-serialize"] }
serde-wasm-bindgen = "0.4.2"
sqlite-vfs = { git = "https://github.com/ProjectAnni/sqlite-vfs" }

[features]
default = ["json"]
db = ["db-read", "db-write"]
db-read = ["rusqlite", "serde_rusqlite"]
db-write = ["rusqlite"]
git = ["git2", "git2-ureq"]
flac = ["anni-flac"]
json = ["serde_json"]
search = ["tantivy", "lindera-tantivy"]
