[package]
name = "anni-repo"
version = "0.1.0"
authors = ["Yesterday17 <mmf@mmf.moe>"]
edition = "2018"

[dependencies]
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_with = "1.10.0"
regex = "1"
anyhow = "1.0"
thiserror = "1.0"
anni-common = { path = "../anni-common" }
anni-derive = { path = "../anni-derive" }
edit = "0.1.2"
uuid = { version = "0.8", features = ["v4", "serde"] }
sqlx = { version = "0.5", features = ["runtime-tokio-rustls", "sqlite"], optional = true }

[features]
default = []
arc = ["anni-common/arc"]
db = ["sqlx"]
