[package]
name = "anni-repo"
version = "0.1.0"
authors = ["Yesterday17 <mmf@mmf.moe>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_with = "1.10.0"
regex = "1"
anyhow = "1.0"
thiserror = "1.0"
anni-common = { path = "../anni-common", default-features = false }
uuid = { version = "0.8", features = ["v4", "serde"] }
log = "0.4.0"
git2 = { version = "0.14", optional = true, features = ["vendored-openssl", "vendored-libgit2"] }

# Database
rusqlite = { version = "0.27.0", optional = true, features = ["uuid", "bundled", "serde_json"] }
serde_rusqlite = { version = "0.30.1", optional = true }

# WASM dependencies
[target.wasm32-unknown-unknown.dependencies]
getrandom = { version = "0.2", features = ["js"] }
js-sys = "0.3"
uuid = { version = "0.8", features = ["v4", "serde", "wasm-bindgen"] }

[features]
default = []
arc = ["anni-common/arc"]
db = ["db-read", "db-write"]
db-read = ["rusqlite", "serde_rusqlite"]
db-write = ["rusqlite"]
git = ["git2"]
wasm = ["db"]
