refresh_rate = "30 seconds"

[appenders.stderr]
kind = "console"
target = "stderr"
encoder = { pattern = "[{h({l})}][{t}] {m}{n}" }

[root]
level = "warn"
appenders = ["stderr"]

[loggers]
"i18n_embed::requester" = { level = "error" }
"anni" = { level = "info" }