## anni
anni-about = A set of tools for self-hosting music sites.


## flac
flac = Provide FLAC-related utilities.
flac-export = Export data.
flac-export-type = Type of data to export.
flac-export-to = Path for exported data.


## split
split = Provided helper to split audios.
split-format-input = Extension of input audio file.
split-format-output = Format of output audio file.
split-apply-tags = Write tags extracted from CUE files to audio file.


## convention
## FIXME
convention = Provided audio convention utilities.
convention-check = Check audio.


## repo
repo = Anni metadata repository manager.
repo-root = Root path of Anni metadata repository to manage.

repo-add = Add new album to repository.
repo-add-edit = Open text editor after album metadata file is crated.
repo-add-invalid-album = Invalid album folder name format.
repo-album-exists = Album with catalog {$catalog} already exists in repo.
repo-album-not-found = Album with catalog {$catalog} was not found in repo.
repo-album-info-mismatch = Album info mismatch with folder.

repo-edit = Open text editor for an album if metadata exists.
repo-apply = Apply metadata from repository to album.
repo-validate = Check whether data in repository is valid.

repo-print = Print metadata information of given catalog.
repo-print-type = Print type.
repo-print-clean = Do not print REM COMMENT "Generated by Anni" in cue mode.
repo-print-catalog = Catalog to print. '/{"{disc_id}"}' can be appended to indicate the disc id of an album. Disc id equals to 0 or 1 both indicates the first disc.


## get
get = Get information from outer API.
get-vgmdb = VGMdb API
get-vgmdb-catalog = Get info from catalog.