//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

pub mod prelude;

pub mod album;
pub mod album_tag_relation;
pub mod catalog_artist;
pub mod catalog_release;
pub mod catalog_source;
pub mod catalog_source_release;
pub mod catalog_source_release_revision;
pub mod catalog_sync_run;
pub mod collection_copy;
pub mod disc;
pub mod ingest_job;
pub mod ingest_metadata_revision;
pub mod sea_orm_active_enums;
pub mod tag_info;
pub mod tag_relation;
pub mod track;
