//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "metadata_organize_level"
)]
pub enum MetadataOrganizeLevel {
    #[sea_orm(string_value = "finished")]
    Finished,
    #[sea_orm(string_value = "initial")]
    Initial,
    #[sea_orm(string_value = "partial")]
    Partial,
    #[sea_orm(string_value = "reviewed")]
    Reviewed,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "tag_type")]
pub enum TagType {
    #[sea_orm(string_value = "animation")]
    Animation,
    #[sea_orm(string_value = "artist")]
    Artist,
    #[sea_orm(string_value = "game")]
    Game,
    #[sea_orm(string_value = "group")]
    Group,
    #[sea_orm(string_value = "organization")]
    Organization,
    #[sea_orm(string_value = "others")]
    Others,
    #[sea_orm(string_value = "project")]
    Project,
    #[sea_orm(string_value = "radio")]
    Radio,
    #[sea_orm(string_value = "series")]
    Series,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "track_type")]
pub enum TrackType {
    #[sea_orm(string_value = "absolute")]
    Absolute,
    #[sea_orm(string_value = "drama")]
    Drama,
    #[sea_orm(string_value = "instrumental")]
    Instrumental,
    #[sea_orm(string_value = "normal")]
    Normal,
    #[sea_orm(string_value = "radio")]
    Radio,
    #[sea_orm(string_value = "unknown")]
    Unknown,
    #[sea_orm(string_value = "vocal")]
    Vocal,
}
