[package]
name = "anni-flac"
version = "0.2.2"
authors = ["Yesterday17 <mmf@mmf.moe>"]
edition = "2018"

[dependencies]
hex = "0.4.2"
thiserror = "1.0"
byteorder = "1"
num-traits = "0.2"
num-derive = "0.3"
image = "0.23.14"

[dev-dependencies]
tempfile = "3.2.0"